<?php

use Tests\TestCase;

class _HomePageTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetHomePage(): void
    {
        $this->get('')
            ->assertViewIs('home');
    }
}